In [1]:
import pandas as pd
data = {
    "unique_id": [
        "DD37Cf93aecA6Dc",
        "1Ef7b82A4CAAD10",
        "6F94879bDAfE5a6",
        "5Cef8BFA16c5e3c",
        "053d585Ab6b3159"
    ],
    "first_name": [
        "Sheryl",
        "Preston",
        "Roy",
        "Linda",
        "Joanna"
    ],
    "last_name": [
        "Baxter",
        "Lozano",
        "Berry",
        "Olsen",
        "Bender"
    ],
    "company": [
        "Rasmussen Group",
        "Vega-Gentry",
        "Murillo-Perry",
        "Dominguez, Mcmillan and Donovan",
        "Martin, Lang and Andrade"
    ],
    "address": [
        "East Leonard",
        "East Jimmychester",
        "Isabelborough",
        "Bensonview",
        "West Priscilla"
    ],
    "country": [
        "Chile",
        "Djibouti",
        "Antigua and Barbuda",
        "Dominican Republic",
        "Slovakia (Slovak Republic)"
    ],
    "phone1": [
        "229.077.5154",
        "5153435776",
        "+1-539-402-0259",
        "001-808-617-6467x12895",
        "001-234-203-0635x76146"
    ],
    "phone2": [
        "397.884.0519x718",
        "686-620-1820x944",
        "(496)978-3969x58947",
        "+1-813-324-8756",
        "001-199-446-3860x3486"
    ],
    "email": [
        "zunigavanessa@smith.info",
        "vmata@colon.com",
        "beckycarr@hogan.com",
        "stanleyblackwell@benson.org",
        "colinalvarado@miles.net"
    ],
    "date": [
        "2020-08-24",
        "2021-04-23",
        "2020-03-25",
        "2020-06-02",
        "2021-04-17"
    ],
    "website": [
        "http://www.stephenson.com/",
        "http://www.hobbs.com/",
        "http://www.lawrence.com/",
        "http://www.good-lyons.com/",
        "https://goodwin-ingram.com"
    ]
} 
df_1 = pd.read_csv("C:\\Users\\kamal\\Downloads\\customers-100.csv")
df = pd.DataFrame(data)
df_1

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [2]:
rows_1 ,columns_1 = df_1.shape
rows , column = df.shape

In [3]:
rows_1

100

In [4]:
rows

5

In [5]:
df_1.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [6]:
df_1.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [7]:
df_1.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [8]:
df_1["Customer Id"]

0     DD37Cf93aecA6Dc
1     1Ef7b82A4CAAD10
2     6F94879bDAfE5a6
3     5Cef8BFA16c5e3c
4     053d585Ab6b3159
           ...
95    cb8E23e48d22Eae
96    CeD220bdAaCfaDf
97    28CDbC0dFe4b1Db
98    c23d1D9EE8DEB0A
99    2354a0E336A91A1
Name: Customer Id, Length: 100, dtype: object

In [9]:
df_1[['Index','Customer Id','First Name','Company']]

    Index      Customer Id First Name                          Company
0       1  DD37Cf93aecA6Dc     Sheryl                  Rasmussen Group
1       2  1Ef7b82A4CAAD10    Preston                      Vega-Gentry
2       3  6F94879bDAfE5a6        Roy                    Murillo-Perry
3       4  5Cef8BFA16c5e3c      Linda  Dominguez, Mcmillan and Donovan
4       5  053d585Ab6b3159     Joanna         Martin, Lang and Andrade
..    ...              ...        ...                              ...
95     96  cb8E23e48d22Eae       Karl                        Carey LLC
96     97  CeD220bdAaCfaDf       Lynn            Ware, Burns and Oneal
97     98  28CDbC0dFe4b1Db       Fred                    Schmitt-Jones
98     99  c23d1D9EE8DEB0A     Yvonne               Fitzgerald-Harrell
99    100  2354a0E336A91A1   Clarence               Le, Nash and Cross

[100 rows x 4 columns]

In [10]:
df_1["Index"].max()

100

In [11]:
df_1.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [12]:
df_1[df_1['Country'] == 'Sri Lanka']

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
13,14,A08A8aF8BE9FaD4,Kristine,Cox,Carpenter-Cook,Jodyberg,Sri Lanka,786-284-3358x62152,+1-315-627-1796x8074,holdenmiranda@clarke.com,2021-02-08,https://www.brandt.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/

In [13]:
df_1.index

RangeIndex(start=0, stop=100, step=1)

In [14]:
df_1.set_index('Country',inplace = True)

In [15]:
df_1

,Index,Customer Id,First Name,Last Name,Company,City,Phone 1,Phone 2,Email,Subscription Date,Website
Country,,,,,,,,,,,
Chile,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
Djibouti,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
Antigua and Barbuda,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
Dominican Republic,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
Slovakia (Slovak Republic),5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...
Guyana,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
Sri Lanka,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
Solomon Islands,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
Aruba,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
Honduras,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/